version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secr3t!
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db